### ISSUE TITLE
Completed Node background image

### ISSUE THREAD

**Issue by MyNameIsEgorA** [KeyValueSoftwareSystems/react-stepper#24]
I found that in completed node there is a default image -check mark - that you can't delete/overwrite.
Maybe I didn't found how to do that, but there is no info in docs

**Comment by MyNameIsEgorA** [comment]
The only way to fix this issue is to manually change styles with css

**Comment by ReshmaJoshy** [comment]
@MyNameIsEgorA  At the moment, our package doesn't support using custom images solely for completed nodes. However, you can use the renderNode function to customize all nodes. In this case, you'll need to manually check the completed status of each node and apply custom styles accordingly. Please note that you'll have to implement custom styling for both completed and incomplete nodes to achieve your desired result. 

```
renderNode={(step, stepIndex) => (
  <div
    key={stepIndex}
    style={{
      backgroundColor: step.completed ? 'green' : 'blue',
      padding: '10px',
      borderRadius: '5px',
      color: 'white',
    }}
  >
    {step.stepLabel}
  </div>
)}
```


Let me know if you need further guidance on how to do this!
